# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EMjdJVmiTmp8MijIkxI70nhmNYdXnMh5

# Final Project NN

**Medical Diagnosis**

`1. Import Libraries`
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

"""`2.  Load Dataset`

"""

df = pd.read_csv("/content/heart.csv")

# Show first 5 rows
print(df.head())

"""
`3. Data Exploration`


"""

print("\nDataset Shape:")
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDataset Info:")
print(df.info())

"""


`4. Data Preprocessing`

"""

# Features and target
X = df.drop("target", axis=1)
y = df["target"]

"""


`5. Split Dataset`


"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""
`6. Feature Scaling`





"""

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""`7. Build MLP Model`



"""

model = Sequential()

# Input + Hidden Layer 1
model.add(Dense(
    64,
    activation='relu',
    input_shape=(X_train.shape[1],)
))

# Hidden Layer 2
model.add(Dense(32, activation='relu'))

# Output Layer
model.add(Dense(1, activation='sigmoid'))

"""


`8. Compile Model`


"""

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Model Summary
print("\nModel Summary:")
model.summary()

"""


`9. Train Model`


"""

history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=16,
    verbose=1
)

"""

`10. Evaluate Model`


"""

loss, accuracy = model.evaluate(X_test, y_test)

print("Test Accuracy:", accuracy)
print("Final Loss:", loss)

"""


`11. Predictions`


"""

y_pred_prob = model.predict(X_test)

# Convert probabilities to 0 or 1
y_pred = (y_pred_prob > 0.5).astype(int)

"""`12. Accuracy Score`"""

acc = accuracy_score(y_test, y_pred)

print(f"Accuracy Score: {acc*100:.2f}")
print()

"""`13. Confusion Matrix`

"""

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

"""

`14. Classification Report`

"""

print("Classification Report:")
print(classification_report(y_test, y_pred))

"""
` 15. Visualization`
"""

# -------- Loss Curve --------

plt.figure(figsize=(8,5))

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')

plt.title("Training vs Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()

plt.show()

# -------- Accuracy Curve --------

plt.figure(figsize=(8,5))

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.title("Training vs Validation Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()

plt.show()

"""`16. EXPERIMENT 1`

* Change Activation Function (tanh)
"""

model_exp1 = Sequential()

model_exp1.add(Dense(
    64,
    activation='tanh',
    input_shape=(X_train.shape[1],)
))

model_exp1.add(Dense(32, activation='tanh'))

model_exp1.add(Dense(1, activation='sigmoid'))

model_exp1.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history1 = model_exp1.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=16,
    verbose=0
)

loss1, accuracy1 = model_exp1.evaluate(X_test, y_test)

print("Experiment 1 Results")
print(f"Accuracy:, {accuracy1*100:.2f}%")
print(f"Loss:, {loss1*100:.2f}%")

"""`17. EXPERIMENT 2`
* Add Dropout
"""

model_exp2 = Sequential()

model_exp2.add(Dense(
    64,
    activation='relu',
    input_shape=(X_train.shape[1],)
))

# Dropout Layer
model_exp2.add(Dropout(0.3))

model_exp2.add(Dense(32, activation='relu'))

model_exp2.add(Dense(1, activation='sigmoid'))

model_exp2.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history2 = model_exp2.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=16,
    verbose=0
)

loss2, accuracy2 = model_exp2.evaluate(X_test, y_test)


print("Experiment 2 Results")
print(f"Accuracy: {accuracy2*100:.2f}%")
print(f"Loss: {loss2*100:.2f}%")

"""` 18. Final Comparison`"""

print("\n================================================")
print("FINAL COMPARISON")
print("================================================")

print(f"Base Model Accuracy   :{accuracy*100:.2f}%")
print(f"Experiment 1 Accuracy :{accuracy1*100:.2f}%")
print(f"Experiment 2 Accuracy :{accuracy2*100:.2f}%")

print(f"Base Model Loss       :{loss*100:.2f}%")
print(f"Experiment 1 Loss     :{loss1*100:.2f}%")
print(f"Experiment 2 Loss     :{loss2*100:.2f}%")